apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flink-ha-role
rules:
- apiGroups: [""]
  resources:
    - configmaps
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-ha-rolebinding
  namespace: flink
subjects:
- kind: ServiceAccount
  name: flink-service-account
  namespace: flink
roleRef:
  kind: ClusterRole
  name: flink-ha-role
  apiGroup: rbac.authorization.k8s.io